import { useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowUpRight, BarChart3, CalendarDays, Camera, Check, Clapperboard, Compass, Image, Layers3, Menu, MessageCircle, Plus, Send, Sparkles, Target, WandSparkles, X, Zap } from 'lucide-react'
import './App.css'

const services = [['01', 'AI Content Creation', 'Generate high-quality posts, carousels, product creatives and visual content using modern AI workflows.', WandSparkles], ['02', 'Reels & Short-Form Content', 'Create engaging short-form videos designed to earn attention on Instagram and beyond.', Clapperboard], ['03', 'Social Media Management', 'Content, captions, hashtags, publishing and the everyday details of your social presence.', Camera], ['04', 'Content Strategy', 'Build a consistent content strategy around your brand, audience and business goals.', Compass], ['05', 'Scheduling & Publishing', 'Plan your content calendar and schedule posts so your social media stays consistent.', CalendarDays], ['06', 'Ad Creatives', 'Create scroll-stopping creative systems for paid advertising campaigns.', Target]]
const projects = [
  { title: 'Onda Coffee', type: 'Social Media', tag: 'Brand system', tone: 'orange', icon: 'O', industry: 'Food & beverage', challenge: 'Build a visual world for a new specialty coffee brand.', direction: 'Warm editorial product stories with a sharp, modern rhythm.', produced: '12 posts, 2 carousels, 4 reels thumbnails' },
  { title: 'Modo Objects', type: 'Product Creatives', tag: 'Product launch', tone: 'lime', icon: 'M', industry: 'Consumer products', challenge: 'Make everyday design objects feel collectible and desirable.', direction: 'High-contrast studio compositions with tactile details.', produced: '16 product creatives, launch carousel, ad set' },
  { title: 'Luma Health', type: 'Branding', tag: 'Visual identity', tone: 'blue', icon: 'L', industry: 'Health tech', challenge: 'Turn a complex health platform into an approachable brand.', direction: 'Electric blue, soft gradients and human-centered diagrams.', produced: 'Brand toolkit, 10 social templates, content pillars' },
  { title: 'Sway Studio', type: 'Reels', tag: 'Motion studies', tone: 'pink', icon: 'S', media: '/portfolio/reels.mp4', industry: 'Creative studio', challenge: 'Give a creative studio a feed with movement and energy.', direction: 'Punchy type, graphic rhythm and intentional frame breaks.', produced: '8 reels, cover system, monthly content direction' },
  { title: 'Arc Finance', type: 'Ads', tag: 'Campaign creative', tone: 'violet', icon: 'A', industry: 'Fintech', challenge: 'Make financial education feel clear, not clinical.', direction: 'Modular cards, decisive headlines and useful visual metaphors.', produced: 'Paid social creative suite, 3 campaign concepts' },
  { title: 'Terra Run Club', type: 'Social Media', tag: 'Community', tone: 'green', icon: 'T', industry: 'Fitness & community', challenge: 'Build a recognizable community signal from the ground up.', direction: 'Kinetic typography with candid, high-energy composition.', produced: 'Content calendar, launch campaign, event templates' },
]
const faqs = [['What type of businesses do you work with?', 'We work with early-stage startups, small businesses and founder-led brands that want a sharper, more consistent presence online.'], ['Do you create the content from scratch?', 'Yes. We develop the creative direction, write the copy and produce the visual content around your brand assets and goals.'], ['Can you manage our Instagram account?', 'Absolutely. We can manage the full workflow from planning and creation to scheduling, publishing and optimization.'], ['Do you schedule and publish posts?', 'Yes. Every plan can include a content calendar and scheduled publishing so your team always knows what is going live.'], ['Can you create reels?', 'Yes. We create short-form concepts, scripts, edit-ready assets and cover systems tailored to your audience.'], ['How does the onboarding process work?', 'We start with a focused brand and goals session, then turn that context into a clear creative direction and first content sprint.'], ['Can we request revisions?', 'Yes. Feedback is built into our workflow so the content feels unmistakably like your brand.'], ['Can you work with our existing brand identity?', 'That is often the best place to start. We can follow, refine or extend an existing identity across social formats.']]
const reveal = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: 0.65 } } }
function Logo({ onClick }) { return <button className="logo flex items-center gap-2" onClick={onClick}><img src="/logo-light.png" alt="adwertize" className="w-6 h-6 object-contain" /><span>adwertize</span></button> }
function Button({ children, outline = false, onClick, type = 'button' }) { return <button type={type} className={`button ${outline ? 'button-outline' : 'button-primary'}`} onClick={onClick}>{children} <ArrowUpRight size={16} /></button> }
function SectionHeading({ eyebrow, title, copy }) { return <div className="section-heading"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div><p>{copy}</p></div> }

function App() {
  const [menuOpen, setMenuOpen] = useState(false), [filter, setFilter] = useState('All'), [selectedProject, setSelectedProject] = useState(null), [openFaq, setOpenFaq] = useState(null), [submitted, setSubmitted] = useState(false)
  const filteredProjects = filter === 'All' ? projects : projects.filter((project) => project.type === filter)
  const scrollTo = (id) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false) }
  return <div className="site-shell">
    <nav className="nav"><Logo onClick={() => scrollTo('top')} /><div className={`nav-links ${menuOpen ? 'open' : ''}`}><button onClick={() => scrollTo('work')}>Work</button><button onClick={() => scrollTo('services')}>Services</button><button onClick={() => scrollTo('process')}>Process</button><button onClick={() => scrollTo('contact')}>Contact</button></div><button className="nav-cta" onClick={() => scrollTo('contact')}>Start a Project <ArrowUpRight size={16} /></button><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}</button></nav>
    <main id="top">
      <section className="hero section-pad"><div className="hero-copy"><div className="eyebrow"><span className="pulse-dot" /> AI-POWERED SOCIAL GROWTH</div><h1>Your brand deserves <em>more</em> than just posts.</h1><p>AI-powered content, social media management and creative strategy built for ambitious startups.</p><div className="hero-actions"><Button onClick={() => scrollTo('contact')}>Start a Project</Button><button className="text-button" onClick={() => scrollTo('work')}>View Our Work <ArrowUpRight size={16} /></button></div><div className="trust-line">Content <span>•</span> Strategy <span>•</span> Management <span>•</span> Growth</div></div><HeroVisual /></section>
      <motion.section className="section-pad services-section" id="services" variants={reveal} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.15 }}><SectionHeading eyebrow="WHAT WE DO" title={<>Everything your social<br /><em>media needs.</em></>} copy="Your ideas deserve a presence that feels as ambitious as the business behind them." /><div className="service-grid">{services.map(([number, title, copy, Icon]) => <motion.article className="service-card" key={title} whileHover={{ y: -6 }}><div className="card-top"><span className="number">{number}</span><Icon size={22} /></div><h3>{title}</h3><p>{copy}</p><ArrowUpRight className="card-arrow" size={18} /></motion.article>)}</div></motion.section>
      <section className="section-pad work-section" id="work"><SectionHeading eyebrow="SELECTED WORK" title={<>Work that speaks<br /><em>for the brand.</em></>} copy="Sample work to show the range of what we can build together. Real projects, coming soon." /><div className="filter-row">{['All', 'Social Media', 'Branding', 'Product Creatives', 'Reels', 'Ads'].map((item) => <button className={filter === item ? 'active' : ''} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><motion.div className="portfolio-grid" layout>{filteredProjects.map((project) => <motion.button className={`project-card ${project.tone}`} key={project.title} layout onClick={() => setSelectedProject(project)}><div className="sample-label">SAMPLE WORK <ArrowUpRight size={14} /></div><div className="project-art">{project.media ? <video src={`${project.media}?v=2`} loop autoPlay playsInline aria-label={`${project.title} reel`} /> : <span className="art-icon">{project.icon}</span>}<strong>{project.title}</strong><small>{project.tag}</small></div><div className="project-meta"><span>{project.title}</span><span>{project.type}</span></div></motion.button>)}</motion.div></section>
      <section className="faq-contact section-pad" id="contact"><div className="faq-column"><div className="eyebrow">QUESTIONS, ANSWERED</div><h2>Good to know.</h2><div className="faq-list">{faqs.map(([question, answer], index) => <div className={`faq-item ${openFaq === index ? 'open' : ''}`} key={question}><button onClick={() => setOpenFaq(openFaq === index ? null : index)}><span>{question}</span>{openFaq === index ? <X size={17} /> : <Plus size={17} />}</button><AnimatePresence>{openFaq === index && <motion.p initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}>{answer}</motion.p>}</AnimatePresence></div>)}</div></div><ContactForm submitted={submitted} setSubmitted={setSubmitted} /></section>
    </main><Footer scrollTo={scrollTo} /><AnimatePresence>{selectedProject && <ProjectModal project={selectedProject} close={() => setSelectedProject(null)} />}</AnimatePresence>
  </div>
}
function HeroVisual() { return <div className="hero-visual"><div className="orb orb-one" /><div className="orb orb-two" /><div className="dashboard-card"><div className="dash-top"><span><span className="window-dot" /> adwertize / studio</span><span className="live-tag"><span /> LIVE</span></div><div className="dash-heading"><div><small>CONTENT ENGINE</small><strong>Make noise, <i>beautifully.</i></strong></div><Sparkles size={18} /></div><div className="content-grid"><div className="creative-tile tile-main"><span>NEW DROP</span><strong>Make space<br />for more.</strong><small>ONDA / 2024</small></div><div className="creative-tile tile-purple"><Layers3 size={22} /><strong>Visual<br />systems</strong><small>04 / 12</small></div><div className="creative-tile tile-photo"><div className="photo-shape" /><small>PRODUCT STUDY</small></div><div className="creative-tile tile-black"><span>◉</span><small>REEL / 00:18</small></div></div><div className="dash-bottom"><span><span className="status-dot" /> 12 pieces in production</span><span>this week <BarChart3 size={14} /></span></div></div><div className="floating-note note-top"><Zap size={14} /> AI-assisted</div><div className="floating-note note-bottom"><span className="mini-avatar">S</span> Your next post is ready</div></div> }
function ContentSystem() { return <section className="system-section section-pad"><SectionHeading eyebrow="THE ADWERTIZE SYSTEM" title={<>Your entire content<br /><em>pipeline. In one place.</em></>} copy="No scattered files. No 'what are we posting today?' Just a clear, living system for your presence." /><div className="system-ui"><aside><div className="system-logo"><span className="logo-mark">✦</span> adwertize</div><div className="side-link active"><CalendarDays size={15} /> Content Calendar</div><div className="side-link"><Image size={15} /> Asset Library</div><div className="side-link"><BarChart3 size={15} /> Performance</div><div className="side-link"><MessageCircle size={15} /> Feedback</div><div className="system-profile"><span className="mini-avatar">S</span><div><strong>Sarah Kim</strong><small>Founder, Modo</small></div></div></aside><div className="system-main"><div className="system-header"><div><small>MONDAY, APRIL 08</small><h3>Content calendar</h3></div><button className="mini-button">+ New post</button></div><div className="calendar-row"><span>MON <b>08</b></span><span className="today">TUE <b>09</b></span><span>WED <b>10</b></span><span>THU <b>11</b></span><span>FRI <b>12</b></span></div><div className="pipeline"><PipelineItem tone="lime" title="Spring / new shapes" kind="Carousel · Instagram" state="Scheduled" /><PipelineItem tone="purple" title="Things worth making" kind="Reel · Instagram" state="Draft" /><PipelineItem tone="orange" title="Slow mornings, better coffee" kind="Post · Instagram" state="Published" /></div></div></div></section> }
function PipelineItem({ tone, title, kind, state }) { return <div className="pipeline-item"><div className={`tiny-art ${tone}`}>{tone === 'purple' ? '✦' : tone === 'orange' ? 'O' : 'M'}</div><div><strong>{title}</strong><small>{kind}</small></div><span className={`pill ${state.toLowerCase()}`}>{state}</span></div> }
function ContactForm({ submitted, setSubmitted }) { return <div className="contact-column"><div className="eyebrow">LET'S TALK</div><h2>Let's build<br /><em>your brand.</em></h2><p>Have a startup or small business that needs better social media? Let's talk.</p><div className="contact-details"><a href="mailto:contact@adwertize.com">contact@adwertize.com <ArrowUpRight size={15} /></a><a href="tel:+919110226054">+91 91102 26054 / +91 94487 51826 <ArrowUpRight size={15} /></a><a href="https://www.instagram.com/adwertize_ai?stkn=YzVib25oajUza3hi" target="_blank" rel="noopener noreferrer">@adwertize_ai <ArrowUpRight size={15} /></a></div><form onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }}>{submitted ? <div className="success-message"><Check size={28} /><strong>Message received.</strong><span>We'll be in touch soon.</span></div> : <><div className="form-row"><label>Name<input required placeholder="Your name" /></label><label>Company / Startup<input required placeholder="Your company" /></label></div><div className="form-row"><label>Email<input required type="email" placeholder="you@company.com" /></label><label>Budget Range<select defaultValue="" required><option value="" disabled>Select a range</option><option>Let's discuss</option><option>Under $1k / month</option><option>$1k–$3k / month</option><option>$3k+ / month</option></select></label></div><label>What do you need help with?<input required placeholder="Content, strategy, a full social system..." /></label><label>Message<textarea required rows="3" placeholder="Tell us a little about your brand and goals..." /></label><Button type="submit">Let's Work Together <Send size={16} /></Button></>}</form></div> }
function Footer({ scrollTo }) { return <footer className="footer"><div className="footer-top"><div><Logo onClick={() => scrollTo('top')} /><p>AI-powered social growth<br />for ambitious brands.</p></div><div className="footer-links"><div><small>EXPLORE</small><button onClick={() => scrollTo('work')}>Work</button><button onClick={() => scrollTo('services')}>Services</button><button onClick={() => scrollTo('process')}>Process</button></div><div><small>CONNECT</small><a href="mailto:contact@adwertize.com">Email</a><a href="tel:+919110226054">Call us</a><a href="https://wa.me/919110226054" target="_blank" rel="noopener noreferrer">WhatsApp</a><a href="#contact">Contact</a></div></div></div><div className="footer-bottom"><span>© 2026 adwertize studio</span><span>AI-powered. Human-directed.</span><span>Bengaluru, IN</span></div></footer> }
function ProjectModal({ project, close }) { return <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={close}><motion.div className="project-modal" initial={{ y: 24, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: 24, opacity: 0 }} onClick={(event) => event.stopPropagation()}><button className="close-modal" onClick={close} aria-label="Close project"><X /></button><div className={`modal-art ${project.tone}`}>{project.media ? <video src={project.media} controls playsInline aria-label={`${project.title} reel`} /> : <><span>{project.icon}</span><strong>{project.title}</strong></>}</div><div className="modal-content"><div className="eyebrow">{project.tag} / SAMPLE WORK</div><h2>{project.title}</h2><div className="case-grid"><div><small>INDUSTRY</small><p>{project.industry}</p></div><div><small>CONTENT PRODUCED</small><p>{project.produced}</p></div></div><div className="case-copy"><div><small>THE CHALLENGE</small><p>{project.challenge}</p></div><div><small>CREATIVE DIRECTION</small><p>{project.direction}</p></div></div></div></motion.div></motion.div> }
export default App
